export const SET_SELECTED_CAMPAIGNS = 'SET_SELECTED_CAMPAIGNS';
export const SET_SELECTED_DATASOURCES = 'SET_SELECTED_DATASOURCES';
export const SET_DATA = 'SET_DATA';
export const SET_FORM_DATA = 'SET_FORM_DATA'